### ISSUE TITLE
Footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-vickyantre#1]
Please, take a look at your footer:
![image](https://cloud.githubusercontent.com/assets/25591824/23239483/3693e350-f970-11e6-9c29-b3bcea46a6ec.png)

Align it the way it represent design:
![image](https://cloud.githubusercontent.com/assets/25591824/23239503/4e5813bc-f970-11e6-8fb5-871af46880c2.png)

Let me know if you'll get into any issues with this item

**Comment by vickyantre** [comment]
Is it better now?

**Comment by eko24ive** [comment]
Yes, footer looks really nice right now, good job !
