### ISSUE TITLE
Lines around star

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-vickyantre#2]
Take a close look at two lines near the star:
![image](https://cloud.githubusercontent.com/assets/25591824/23239536/93560168-f970-11e6-8bd4-d9ecb4e8ba88.png)

According to design they have to be longer:
![image](https://cloud.githubusercontent.com/assets/25591824/23239545/9d35c286-f970-11e6-8e26-a0d407dd20d0.png)

Please fix this for all _stars_

**Comment by vickyantre** [comment]
This is a problem I talked about in discord. I just do not know how to do it.

**Comment by eko24ive** [comment]
Look, you don't have to use `.fa.fa-minus` to approach this result.
You may wrap your `.fa.fa-star` into div element, like this:
```html
<div class="star-line">
  <i class="fa fa-star"></i>
</div>
```
And then, using `:before` and `:after` pseudo-classes create a line around the star.
Would you give this a try ?

**Comment by vickyantre** [comment]
Done. This is the only way i could imagine. I know how to use before and after, i do not know how to create long line. That is why i used fa-minus.

**Comment by eko24ive** [comment]
It's fine.
I'm really happy you've figured out for yourself how to do it "the right way".
But what I loved the most - is how you was able to find an easy way out to just get the job done, perfect !
